# Generated by Django 4.0.4 on 2022-07-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_appuser_verification_code_alter_appuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
